controllers:
    resource: ../src/Http/Controller/
    type: annotation
admin_controllers:
    resource: ../src/Http/Admin/Controller/
    type: annotation
    name_prefix: admin_
    prefix: '%admin_prefix%'
kernel:
    resource: ../src/Kernel.php
    type: annotation
