parameters:
    admin_prefix:     '%env(resolve:ADMIN_PREFIX)%'
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $appEnv: '%kernel.environment%'
            $adminPrefix: '%admin_prefix%'
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Infrastructure/Migrations,Tests,Kernel.php}'

    App\Http\Twig\TwigAssetExtension:
        arguments:
            $assetPath: '%kernel.project_dir%/public/assets'
            $env: '%kernel.environment%'

    App\Http\Controller\:
        resource: '../src/Http/Controller'
        tags: ['controller.service_arguments']

    App\Http\Admin\Controller\:
        resource: '../src/Http/Admin/Controller'
        tags: ['controller.service_arguments']

    App\Http\Admin\Firewall\AdminRequestListener:
        arguments: ['%admin_prefix%']

    Knp\Bundle\PaginatorBundle\Helper\Processor: ~

    App\Infrastructure\Helper\Paginator\PaginatorInterface:
        class: App\Infrastructure\Helper\Paginator\KnpPaginator
